name: Build

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          trust-check: false
          version: "v0.2.6"

      - run: |
          yarn
          yarn build

      - uses: fabasoad/data-format-converter-action@main
        id: yaml2json
        with:
          input: "bloxadmin-sdk.rbxmx"
          from: "xml"
          to: "json"

      - name: Print result
        run: echo "${{ steps.yaml2json.outputs.output }} > bloxadmin-sdk.json"

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          files: |
            bloxadmin-sdk.rbxmx
            bloxadmin-sdk.json
